### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by LeviAckerman1234** [KeyAuth/KeyAuth-Discord-Bot#12]
Hi developer amazing code you have however I did npm install and installed all packages but it says module not found when I try to run it let me know if you can help whenever you can, thanks

**Comment by LeviAckerman1234** [comment]
anyone there?

**Comment by wnelson03** [comment]
Please look at Google/YoutTube. Based on the root issue where orf mentioned you in this issue, it appears that you don't understand how to run a Discord bot.

In that case, you should either use the public KeyAuth Discord bot, invite URL https://discord.com/api/oauth2/authorize?client_id=866538681308545054&permissions=0&scope=applications.commands%20bot. Or look at online resources to learn how to run a bot.

It's quite simple. You run the `npm i` command to install the modules then the `node index.js` command to start the bot. The public KeyAuth bot is running on Node.js v16.15.0, so perhaps you should try using the same version of Node.js.
