### ISSUE TITLE
hello bot not working

### ISSUE THREAD

**Issue by Cyporemre** [KeyAuth/KeyAuth-Discord-Bot#9]
bot shuts down with not responding error commands not working

**Comment by mazk5145** [comment]
your own bot?
please provide video clip or ss

**Comment by Cyporemre** [comment]
![image](https://user-images.githubusercontent.com/103285803/174841264-5f4690f6-ab46-41b8-9907-9f080eb247a7.png)

**Comment by mazk5145** [comment]
ok lemme look..

**Comment by mazk5145** [comment]
is every other command working fine?

**Comment by Cyporemre** [comment]
no all dont working

**Comment by mazk5145** [comment]
okay did you modify the example by anyway?

**Comment by mazk5145** [comment]
download latest here, and don't modify anything else than the config file
